name: LinkCheck

on:
  pull_request:
    branches: ['*']
    paths:
      - README.md
  push:
    branches: ['*']
    paths:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker://dkhamsing/awesome_bot:latest
        with:
          args: /github/workspace/README.md --allow-redirect --white-list http://localhost,http://localhost:3000,https://github.com/cwackerfuss/react-wordle/blob/main/.env
